"""
Code generated by ChatGPT 5.0 and adapted
"""

# !/usr/bin/env python3
import argparse
import csv
import json
from pathlib import Path
from typing import Any
from typing import Dict
from typing import List

import pandas as pd


def resource_paths(package_dir: Path, resource: Dict[str, Any]) -> List[Path]:
    p = resource.get("path")
    if p is None:
        raise ValueError(
            f"Resource {resource.get('name', '<unnamed>')} has no 'path'"
        )
    if isinstance(p, str):
        p_list = [p]
    elif isinstance(p, list):
        p_list = p
    else:
        raise TypeError("'path' must be string or list of strings")
    paths: List[Path] = []
    for rel in p_list:
        candidate = (package_dir / rel).resolve()
        # prevent escaping the package dir
        if not str(candidate).startswith(str(package_dir.resolve())):
            raise ValueError(
                f"Unsafe path for resource {resource.get('name')}: {rel}"
            )
        paths.append(candidate)
    return paths


def csv_reader_for_resource(
    fp, resource: Dict[str, Any], *, force_schema_headers: bool = False
):
    dialect = resource.get("dialect", {}) or {}
    delimiter = dialect.get("delimiter", ",")
    quotechar = dialect.get("quoteChar") or dialect.get("quotechar") or '"'
    doublequote = (
        dialect.get("doubleQuote") if "doubleQuote" in dialect else True
    )
    escapechar = dialect.get("escapeChar") or None

    # If schema defines fields and we force schema headers, use them
    fieldnames = None
    if force_schema_headers:
        schema = resource.get("schema") or {}
        if isinstance(schema, dict):
            fields = schema.get("fields") or []
            if fields and all(
                isinstance(f, dict) and "name" in f for f in fields
            ):
                fieldnames = [f["name"] for f in fields]

    if fieldnames is not None:
        return csv.DictReader(
            fp,
            delimiter=delimiter,
            quotechar=quotechar,
            doublequote=doublequote,
            escapechar=escapechar,
            fieldnames=fieldnames,
        )
    else:
        return csv.DictReader(
            fp,
            delimiter=delimiter,
            quotechar=quotechar,
            doublequote=doublequote,
            escapechar=escapechar,
        )


def export_dp_to_json(
    package_dir: Path,
    out_dir: Path = None,
):
    """
    Export a Frictionless Data Package (CSV resources) into a single JSON file.

    This collects all rows from each CSV resource listed in
    ``pkg['resources']`` and writes a single JSON document with two
    top-level keys:

    - ``"metadata"``: the original ``datapackage.json``
      content (``pkg`` as provided)
    - ``"data"``: a dict with the following keys: "index", "column_names" and "values"
        "values" is a list of length N*M, where N is the number of rows and M the number of columns of the resource
         if "index" is an empty list, the number of rows is inferred from the number of columns and the length of the
         "values". If column_names contains lists or tuples, then the columns of the resource are a MultiIndex.

    If a resource’s ``path`` is a list (multi-file resource), rows from all
    files are concatenated into the same list for that resource.

    Parameters
    ----------
    package_dir : pathlib.Path
        Directory containing ``datapackage.json`` and the resource files
        referenced by it.
    out_dir : pathlib.Path
        Destination directory; will be created if it does not exist.

    Returns
    -------
    str
        The absolute path of the written file (``datapackage_export.json``
        inside ``out_dir``) if out_dir is not None, the JSONified datapackage
        otherwise.

    Notes
    -----
    - All JSON is written as UTF-8, with ``ensure_ascii=False`` and pretty
      indentation.
    - This function loads all rows into memory; for very large datasets
      consider using an NDJSON/streaming export instead.

    Raises
    ------
    FileNotFoundError
        If any referenced resource file does not exist.
    ValueError, TypeError
        If a resource has an invalid ``path`` definition or unsafe path
        resolution.
    UnicodeDecodeError
        If a file cannot be decoded with the specified encoding.
    OSError
        For general I/O errors while reading or writing files.

    Examples
    --------
    >>> from pathlib import Path
    >>> import json
    >>> my_pkg = json.loads(Path("my_pkg/datapackage.json").read_text(
    ...     encoding="utf-8"))
    >>> export_dp_to_json(Path("my_pkg"), Path("out"))
    '/abs/path/out/datapackage_export.json'
    """

    dp_path = package_dir / "datapackage.json"
    if not dp_path.exists():
        raise FileNotFoundError(f"datapackage.json not found in {package_dir}")
    with dp_path.open("r", encoding="utf-8") as f:
        pkg = json.load(f)

    data: Dict[str, List[Dict[str, Any]]] = {}
    resources = pkg.get("resources") or []
    for res in resources:
        name = res.get("name") or (
            Path(
                res.get("path")
                if isinstance(res.get("path"), str)
                else "resource"
            ).stem
        )
        if "dialect" not in res:
            header_rows = [0]
            res["dialect"] = {"header": True, "headerRows": header_rows}
        else:
            header_rows = res["dialect"].get("headerRows", [0])

        rows = {"index": [], "columns_names": [], "values": []}
        paths = resource_paths(package_dir, res)
        for p in paths:
            try:
                df = pd.read_csv(
                    p,
                    header=header_rows,
                    index_col=0,
                    parse_dates=[0],
                    na_values="",
                )
                N = len(df.index)

                if df.index.dtype == "str" or df.index.name not in (
                    "index",
                    "timeindex",
                ):
                    df.reset_index(inplace=True)
                    index = []
                else:
                    index = [str(idx) for idx in df.index.values]

                M = len(df.columns)

                if isinstance(df.columns, pd.MultiIndex):
                    cols = [list(c) for c in df.columns]
                else:
                    cols = list(df.columns)

                values = df.values.reshape((M * N,)).tolist()

                rows = {
                    "index": index,
                    "columns_names": cols,
                    "values": values,
                }
            except pd.errors.EmptyDataError:
                print(p, "was empty")
        data[name] = rows

    if out_dir is not None:
        out_dir.mkdir(parents=True, exist_ok=True)
        output_path = out_dir / "datapackage_export.json"
        with output_path.open("w", encoding="utf-8") as out:
            json.dump(
                {"metadata": pkg, "data": data},
                out,
                ensure_ascii=False,
                indent=4,
            )
        answer = str(output_path)
    else:
        # import pdb;pdb.set_trace()
        answer = json.dumps(
            {"metadata": pkg, "data": data}, ensure_ascii=False
        )
    return answer


def main():
    parser = argparse.ArgumentParser(
        description="Export a Frictionless Data Package (CSV resources) "
        "to JSON."
    )
    parser.add_argument(
        "package_dir", help="Path to folder that contains datapackage.json"
    )
    parser.add_argument(
        "--out", "-o", default=".", help="Output folder (default: .)"
    )
    args = parser.parse_args()

    package_dir = Path(args.package_dir).expanduser().resolve()
    out_dir = Path(args.out).expanduser().resolve()

    fpath = export_dp_to_json(package_dir, out_dir)
    print(f"Datapackage exported to JSON into the file '{fpath}'")


if __name__ == "__main__":
    main()
