"""
Code generated by ChatGPT 5.0 and adapted
"""

# !/usr/bin/env python3
import argparse
import csv
import json
from pathlib import Path
from typing import Any
from typing import Dict
from typing import List
from typing import Union

import numpy as np
import pandas as pd


def safe_join(base: Path, rel: Union[str, Path]) -> Path:
    """
    Join base with rel and ensure the result stays within base.
    """
    target = (base / rel).resolve()
    if not str(target).startswith(str(base.resolve())):
        raise ValueError(f"Unsafe path outside output directory: {rel}")
    return target


def dialect_from_resource(res: Dict[str, Any]) -> Dict[str, Any]:
    d = (
        (res.get("dialect") or {})
        if isinstance(res.get("dialect"), dict)
        else {}
    )
    return d


def rebuild_dp_from_json(
    src_file: Path, out_dir: Path, *, overwrite: bool = False
):
    """

    Parameters
    ----------
    src_file: Path or dict
        path to a jsonified datapackage or jsonified datapackage as dict
    out_dir: Path
        path where the recreated datapackage should be saved
    overwrite: bool, default False

    Returns
    -------
    The path of the datapackage.json file within the recreated datapackage
    """
    payload = None
    if isinstance(src_file, dict):
        payload = src_file
    else:
        with src_file.open("r", encoding="utf-8") as f:
            payload = json.load(f)

    out_dir.mkdir(parents=True, exist_ok=True)

    pkg = payload.get("metadata") or {}
    data = payload.get("data") or {}

    if not pkg or "resources" not in pkg:
        raise ValueError(
            "Invalid single-JSON export: missing 'metadata.resources'"
        )

    resources = pkg.get("resources") or []

    updated_resources = []

    for res in resources:
        name = res.get("name") or "resource"
        res["dialect"] = dialect_from_resource(res)
        rows = data.get(name, [])
        path_spec = res.get("path")

        # Determine output strategy based on path type
        if isinstance(path_spec, list):
            if not path_spec:
                raise ValueError(f"Resource '{name}' has empty path list")
            # Use the first path as the write target and collapse to
            # single-file
            target_rel = path_spec[0]
            res["path"] = target_rel  # collapse in metadata for consistency
        elif isinstance(path_spec, str):
            target_rel = path_spec
        else:
            # No path in metadata; fallback to data/<name>.csv
            target_rel = str(Path("data") / f"{name}.csv")
            res["path"] = target_rel

        out_csv = safe_join(out_dir, target_rel)
        if out_csv.exists() and not overwrite:
            raise FileExistsError(
                f"{out_csv} exists (pass --overwrite to replace)"
            )
        else:
            out_csv.parent.mkdir(parents=True, exist_ok=True)

        columns = rows["columns_names"]
        M = len(columns)
        if M > 0:
            if isinstance(columns[0], list):
                columns = pd.MultiIndex.from_tuples(
                    columns, names=["from", "to"]
                )

        index = rows["index"]
        N = len(index)
        if N > 0:
            try:
                float(index[0])
                index = pd.Index(index, name="index")
            except ValueError:
                index = pd.DatetimeIndex(index)
                index.name = "timeindex"

        vals = np.array(rows["values"]).reshape((N, M))
        df = pd.DataFrame(data=vals, columns=columns, index=index)

        df.to_csv(out_csv)

        # Ensure encoding is set to utf-8 in metadata
        res["encoding"] = "utf-8"
        updated_resources.append(res)

    # Write datapackage.json with updated paths/encodings
    dp_out = out_dir / "datapackage.json"

    pkg["resources"] = updated_resources

    with dp_out.open("w", encoding="utf-8") as f:
        json.dump(pkg, f, ensure_ascii=False, indent=4)

    return out_dir


def main():
    ap = argparse.ArgumentParser(
        description="Rebuild a Frictionless Data Package from a single JSON "
        "export, preserving original folder structure."
    )
    ap.add_argument("single_json", help="Path to datapackage in JSON format")
    ap.add_argument(
        "--out", "-o", default=".", help="Output folder (default: .)"
    )
    ap.add_argument(
        "--overwrite", action="store_true", help="Overwrite existing files"
    )
    args = ap.parse_args()

    src = Path(args.single_json).expanduser().resolve()
    out_dir = Path(args.out).expanduser().resolve()

    result = rebuild_dp_from_json(src, out_dir, overwrite=args.overwrite)
    print(f"Datapackage saved under '{result}'")


if __name__ == "__main__":
    main()
